#!/bin/bash

CAVA_CONFIG="$HOME/.config/cava/config"
WAL_COLORS="$HOME/.cache/wal/colors.json"

COLOR1=$(jq -r '.colors.color1' "$WAL_COLORS")
COLOR2=$(jq -r '.colors.color5' "$WAL_COLORS")

sed -i "s|^gradient_color_1 = .*|gradient_color_1 = '$COLOR1'|" "$CAVA_CONFIG"
sed -i "s|^gradient_color_2 = .*|gradient_color_2 = '$COLOR2'|" "$CAVA_CONFIG"

pkill -USR1 cava 2>/dev/null

